Repository Nathan-Etave/Hades, pull requests merged in 2023-12, with the labels that each got.

#55 PR de views_tags vers views
  app/views.py
Labels: Développement

#56 PR de fix/views vers feature/views
  app/static/js/file.js
  app/views.py
Labels: fix

#69 Merge de Fix/ Correction des paramètres
  app/views.py
Labels: fix

#71 Feat/administrateur accueil
  app/static/css/administration.css
  app/templates/administration.html
Labels: Développement

#82 PR de fix/Flask vers feature/Flask
  app/static/css/editCategories.css
  app/static/css/upload.css
  app/static/css/user.css
  app/templates/addUser.html
  app/templates/administration.html
  app/templates/components/header.html
  app/templates/multivue.html
  app/views.py
Labels: fix

#85 merge de Doc/docstring dans feature/Flask
  app/database.py
  app/requests.py
  app/views.py
Labels: documentation
