Repository Nathan-Etave/Hades, pull requests merged in 2023-11, with the labels that each got.

#27 PR de fix/components vers feature/components
  app/static/css/bottomHeader.css
  app/static/css/header.css
  app/static/css/mediaBottomHeader.css
  app/static/css/mediaBottomHeaderSearchBar.css
  app/static/js/header.js
  app/templates/components/bottomHeaderSearchBar.html
  app/templates/components/header.html
Labels: web components

#24 Feature/home
  app/static/css/home.css
  app/templates/home.html
Labels: web templates

#28 fix/tables_BD to feature/tables_BD
  app/bd/create_tables.sql
Labels: BD

#29 PR de feature/components vers feature/templates
  app/static/css/bottomHeader.css
  app/static/css/header.css
  app/static/css/mediaBottomHeader.css
  app/static/css/mediaBottomHeaderSearchBar.css
  app/static/js/header.js
  app/templates/components/bottomHeaderSearchBar.html
  app/templates/components/header.html
  app/templates/components/headerLogin.html
Labels: web components

#23 Feat/connexion to templates
  app/static/css/connexion.css
  app/templates/connexion.html
Labels: web templates

#33 merge fix/documentions into documentations
  docs/UML.drawio
  docs/img/MCD.jpg
  docs/img/MLD.jpg
Labels: documentation

#31 Feature/search
  app/static/css/search.css
  app/templates/search.html
Labels: web templates

#34 merge branche fix/tables_BD into feature/tables_BD
  app/bd/clear_tables.sql
  app/bd/create_tables.sql
  app/bd/drop_tables.sql
Labels: BD

#35 PR de feature/file vers feature/templates
  app/static/css/file.css
  app/static/js/file.js
  app/templates/file.html
Labels: web templates

#39 Documentations into developpement
  docs/UML.drawio
  docs/img/MCD.jpg
  docs/img/MLD.jpg
  docs/rapport.pdf
Labels: documentation

#42 feature/search into feature/templates
  app/static/css/search.css
  app/static/js/search.js
  app/templates/search.html
Labels: web templates

#43 PR de feature/templates dans developpement
  app/static/css/bottomHeader.css
  app/static/css/connexion.css
  app/static/css/file.css
  app/static/css/header.css
  app/static/css/home.css
  app/static/css/mediaBottomHeader.css
  app/static/css/mediaBottomHeaderSearchBar.css
  app/static/css/multivue.css
  app/static/css/notification.css
  app/static/css/search.css
  app/static/css/user.css
  app/static/js/file.js
  app/static/js/header.js
  app/static/js/search.js
  app/templates/baseUser.html
  app/templates/components/bottomHeader.html
  app/templates/components/bottomHeaderSearchBar.html
  app/templates/components/header.html
  app/templates/components/headerLogin.html
  app/templates/connexion.html
  app/templates/editUser.html
  app/templates/file.html
  app/templates/home.html
  app/templates/multivue.html
  app/templates/notification.html
  app/templates/search.html
  app/templates/user.html
Labels: Développement

#44 feature/__init__ into feature/ORM
  .flaskenv
  app/__init__.py
Labels: Développement

#46 PR de feature/init_database vers feature/ORM
  app/database.py
  app/static/csv/A_ACCES.csv
  app/static/csv/A_CONSULTE.csv
  app/static/csv/A_NOTIFICATION.csv
  app/static/csv/A_TAG.csv
  app/static/csv/CATEGORIE.csv
  app/static/csv/DATE.csv
  app/static/csv/EST_CATEGORIE.csv
  app/static/csv/ETAT_FICHIER.csv
  app/static/csv/FAVORI.csv
  app/static/csv/FICHIER.csv
  app/static/csv/HISTORIQUE.csv
  app/static/csv/NOTIFICATION.csv
  app/static/csv/POMPIER.csv
  app/static/csv/ROLE_POMPIER.csv
  app/static/csv/SIGNALEMENT.csv
  app/static/csv/SOUS_CATEGORIE.csv
  app/static/csv/TAG.csv
Labels: Développement

#45 PR de feature/models vers feature/ORM
  app/models.py
Labels: Développement

#50 feature/ Ajout fonctionnalité recherche par catégorie
  app/views.py
Labels: Développement

#51 Feature/get file by categorie
  app/requests.py
Labels: Développement
