Repository Nathan-Etave/Hades, pull requests merged in 2023-10, with the labels that each got.

#13 Feature/PR de components dans templates
  app/static/css/bottomHeader.css
  app/static/css/footer.css
  app/static/css/header.css
  app/static/css/mediaBottomHeader.css
  app/static/css/mediaBottomHeaderSearchBar.css
  app/static/js/header.js
  app/templates/components/bottomHeader.html
  app/templates/components/bottomHeaderSearchBar.html
  app/templates/components/footer.html
  app/templates/components/header.html
  app/templates/components/headerLogin.html
Labels: web components

#14 Merge de feature/templates dans developpement
  app/static/css/bottomHeader.css
  app/static/css/footer.css
  app/static/css/header.css
  app/static/css/mediaBottomHeader.css
  app/static/css/mediaBottomHeaderSearchBar.css
  app/static/js/header.js
  app/templates/components/bottomHeader.html
  app/templates/components/bottomHeaderSearchBar.html
  app/templates/components/footer.html
  app/templates/components/header.html
  app/templates/components/headerLogin.html
Labels: web templates

#15 Feature/PR de tables_bd vers developpement
  app/bd/clear_tables.sql
  app/bd/create_tables.sql
  app/bd/drop_tables.sql
Labels: BD

#16 Feature/PR insert_BD to developpement
  app/bd/insert_tables.sql
Labels: BD

#17 Fix/documentations to documentations
  README.md
  docs/Maquettes.fig
  docs/UML.drawio
  docs/img/Description textuelle _ Gerer notification.jpg
  docs/img/Description textuelle _ Se connecter .jpg
  docs/img/Description textuelle_ Administre Catégorie.jpg
  docs/img/Description textuelle_ Administrer les fichiers.jpg
  docs/img/Description textuelle_ Administrer les profils .jpg
  docs/img/Description textuelle_ Consulter l_historique récent.jpg
  docs/img/Description textuelle_ Consulter les consultations .jpg
  docs/img/Description textuelle_ Gerer favoris.jpg
  docs/img/Description textuelle_ Gerer profil.jpg
  docs/img/Description textuelle_ Rechercher fichier.jpg
  docs/img/Diagramme d_activité_ Gestion fichier.jpg
  docs/img/Diagramme d_activité_ Recherche fichier.jpg
  docs/img/MCD.jpg
  docs/img/MLD.jpg
  docs/img/diagramme-Cas d_utilisation.jpg
  docs/rapport.pdf
Labels: documentation

#18 Merge de la branche de documentation dans la branche de developpment
  README.md
  docs/Maquettes.fig
  docs/UML.drawio
  docs/img/Description textuelle _ Gerer notification.jpg
  docs/img/Description textuelle _ Se connecter .jpg
  docs/img/Description textuelle_ Administre Catégorie.jpg
  docs/img/Description textuelle_ Administrer les fichiers.jpg
  docs/img/Description textuelle_ Administrer les profils .jpg
  docs/img/Description textuelle_ Consulter l_historique récent.jpg
  docs/img/Description textuelle_ Consulter les consultations .jpg
  docs/img/Description textuelle_ Gerer favoris.jpg
  docs/img/Description textuelle_ Gerer profil.jpg
  docs/img/Description textuelle_ Rechercher fichier.jpg
  docs/img/Diagramme d_activité_ Gestion fichier.jpg
  docs/img/Diagramme d_activité_ Recherche fichier.jpg
  docs/img/MCD.jpg
  docs/img/MLD.jpg
  docs/img/diagramme-Cas d_utilisation.jpg
  docs/rapport.pdf
Labels: documentation
