Repository Nathan-Etave/Hades, pull requests merged in 2024-05, with the labels that each got.

#126 merge de la branche Feat/utilisateur dans dev
  app/home/routes.py
  app/static/css/home.css
  app/static/js/home.js
  app/static/js/preview.js
  app/templates/home/index.html
Labels: Développement

#128 PR: Merge de feat/administration dans dev
  app/administration/routes.py
  app/models/dossier.py
  app/static/css/base.css
  app/static/js/administration.js
  app/tasks.py
  app/templates/administration/index.html
  app/templates/base.html
  app/utils.py
Labels: enhancement, dev

#129 Merge de feat/utilisateur dans dev
  app/notifications/routes.py
  app/static/css/home.css
  app/static/css/notifications.css
  app/static/js/notifications.js
  app/static/js/preview.js
  app/templates/home/index.html
  app/templates/notifications/index.html
Labels: dev

#130 Merge de la branche Feat/utilisateur dans dev
  app/administration/routes.py
  app/decorators.py
  app/desktop/__init__.py
  app/desktop/routes.py
  app/file_handler/__init__.py
  app/file_handler/routes.py
  app/forms/edit_profil_form.py
  app/forms/registration_form.py
  app/home/routes.py
  app/login/routes.py
  app/profil/__init__.py
  app/profil/routes.py
  app/static/js/base.js
  app/static/js/desktop.js
  app/static/js/login.js
  app/static/js/profil.js
  app/templates/components/desktop_preview.html
  app/templates/desktop/index.html
  app/templates/login/index.html
  app/templates/profil/index.html
  app/utils.py
Labels: documentation, dev

#131 PR: Merde feat/administration dans dev
  app/__init__.py
  app/administration/routes.py
  app/mail/mail.py
  app/models/fichier.py
  app/notifications/routes.py
  app/static/css/notifications.css
  app/static/js/notifications.js
  app/static/js/preview.js
  app/tasks.py
  app/templates/home/index.html
  app/templates/notifications/index.html
Labels: enhancement, dev

#132 PR: Merge de feat/alerts dans dev
  app/__init__.py
  app/administration/routes.py
  app/forms/edit_profil_form.py
  app/notifications/routes.py
  app/profil/__init__.py
  app/profile/__init__.py
  app/profile/routes.py
  app/static/css/profile.css
  app/static/js/administration.js
  app/static/js/desktop.js
  app/static/js/home.js
  app/static/js/login.js
  app/static/js/notifications.js
  app/static/js/profile.js
  app/templates/base.html
  app/templates/notifications/index.html
  app/templates/profile/index.html
  app/utils.py
Labels: enhancement, dev, fix

#134 Merge de la branche feat/details dans dev
  app/__init__.py
  app/administration/routes.py
  app/celery.py
  app/decorators.py
  app/desktop/routes.py
  app/extensions.py
  app/file_handler/routes.py
  app/home/routes.py
  app/login/routes.py
  app/mail.py
  app/models/a_recherche.py
  app/models/favoris.py
  app/models/fichier.py
  app/models/lien.py
  app/models/notification.py
  app/models/utilisateur.py
  app/notifications/routes.py
  app/profile/routes.py
  app/register/routes.py
  app/static/hades.webmanifest
  app/static/img/android-chrome-192x192.png
  app/static/img/android-chrome-512x512.png
  app/static/img/apple-touch-icon.png
  app/static/img/favicon-16x16.png
  app/static/img/favicon-32x32.png
  app/static/img/favicon.ico
  app/static/js/administration.js
  app/static/js/desktop.js
  app/static/js/home.js
  app/tasks.py
  app/templates/administration/index.html
  app/templates/base.html
  app/templates/desktop/index.html
  app/templates/home/index.html
  config.py
  requirements.txt
Labels: enhancement, dev, fix

#135 Merge de la branche feat/utilisateur dans dev
  app/__init__.py
  app/forms/password_reset_form.py
  app/forms/registration_form.py
  app/home/routes.py
  app/login/routes.py
  app/mail.py
  app/notifications/routes.py
  app/password_reset/__init__.py
  app/password_reset/routes.py
  app/register/routes.py
  app/static/js/home.js
  app/static/js/password_reset.js
  app/templates/password_reset/index.html
  app/templates/register/index.html
  app/utils.py
Labels: enhancement, dev

#138 Merge Feat/utilisateur dans dev
  app/static/js/preview.js
  app/templates/administration/index.html
  app/templates/notifications/index.html
Labels: fix

#137 PR: feat/docker - details dans dev
  app/administration/routes.py
  app/login/routes.py
  app/models/fichier.py
  app/models/notification.py
  app/models/utilisateur.py
  app/static/css/home.css
  app/static/js/administration.js
  app/static/js/desktop.js
  app/static/js/home.js
  app/static/js/preview.js
  app/tasks.py
  app/templates/administration/index.html
  app/templates/desktop/index.html
  app/templates/home/index.html
  app/templates/notifications/index.html
  app/utils.py
Labels: enhancement, bd, dev, fix

#139 Merge de Feat/utilisateur dans dev
  app/static/js/home.js
  app/static/js/notifications.js
  app/static/js/preview.js
  app/templates/home/index.html
  app/templates/notifications/index.html
Labels: enhancement, dev, fix

#140 Fix/ correction attribution event home
  app/static/css/base.css
  app/static/js/home.js
  app/templates/home/index.html
Labels: dev, fix

#141 merge de Feat/utilisateur dans dev
  app/forms/edit_profil_form.py
  app/home/routes.py
  app/static/js/home.js
  app/templates/home/index.html
  app/templates/profile/index.html
  app/utils.py
Labels: enhancement, dev

#142 PR: feat/bureau dans dev
  app/__init__.py
  app/administration/routes.py
  app/static/js/administration.js
  app/static/js/preview.js
  app/tasks.py
  app/utils.py
  requirements.txt
Labels: bd, dev
